server:
  port: 7900
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: microservice-provider-user # 建议小写
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.lhx: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:a123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map: 
      zone: ABC # zone默认带的  eureka可以理解的数据
      lihongxu: BBC # 自定义的 不会影响客户端行为
    appname: USER-SERVICE-HAHA

management:
  port: 11112   #actuator暴露接口使用的端口，为了和api接口使用的端口进行分离
  context-path: /admin   #actuator暴露接口的前缀
  security:
    enabled: true   #actuator是否需要安全保证
    roles: SUPERUSER
security:
  basic:
    enabled: true
    path: /admin    #针对/admin路径进行认证
  user:
    name: admin
    password: password